// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFt9SKDlxuZsuDKOGy5JeXuWSF1PsFkas',
    appId: '1:650825982023:web:6063930ea3de50d6bfd162',
    messagingSenderId: '650825982023',
    projectId: 'nludo-flutter',
    authDomain: 'nludo-flutter.firebaseapp.com',
    storageBucket: 'nludo-flutter.appspot.com',
    measurementId: 'G-V2B025RXBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA25c_j2oAVWtu711tpOjLlMW2WsfWdKU8',
    appId: '1:650825982023:android:d46161865afe57dabfd162',
    messagingSenderId: '650825982023',
    projectId: 'nludo-flutter',
    storageBucket: 'nludo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5E1VTSlyEmGHPxwv4pSlCGxvLiu7IlQY',
    appId: '1:650825982023:ios:a9df1f0929639785bfd162',
    messagingSenderId: '650825982023',
    projectId: 'nludo-flutter',
    storageBucket: 'nludo-flutter.appspot.com',
    iosClientId: '650825982023-3v5b6rg4n276k4urhn5mnkrh1458v3tn.apps.googleusercontent.com',
    iosBundleId: 'dev.nizwar.ludo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5E1VTSlyEmGHPxwv4pSlCGxvLiu7IlQY',
    appId: '1:650825982023:ios:84120cd4b6eb785fbfd162',
    messagingSenderId: '650825982023',
    projectId: 'nludo-flutter',
    storageBucket: 'nludo-flutter.appspot.com',
    iosClientId: '650825982023-jhoaqhiqo525rj6t3j3u4bq2je23c798.apps.googleusercontent.com',
    iosBundleId: 'com.example.ludoFlutter',
  );
}
